feat: options to require agreements to ts and cs and pp explicitly
StakeNow/SIWT-Deprecated pull request #18
Opened 2022-11-07 13:57 UTC by royscheeren

# Scope

Add options to the create message function to require users to explicitly agree to terms and conditions and/or privacy policy.

# Work done
Added an options object to the parameters of the createMessagePayload function to add the required sentences to the message.

2022-11-14 10:13 UTC, jdsika commented
new linter options used? Can we put the linter options into the CONTRIBUTING.md?

2022-11-14 10:16 UTC, jdsika requested changes

2022-11-14 10:16 UTC, jdsika commented on src/siwt.ts
> -  async ({ contractAddress, network = Network.ithacanet, parameters: { pkh }, test: { comparator, value } }: AccessControlQuery) => {
ghostnet

2022-11-14 12:16 UTC, royscheeren commented on src/siwt.ts
> -  async ({ contractAddress, network = Network.ithacanet, parameters: { pkh }, test: { comparator, value } }: AccessControlQuery) => {
This will change with #19

2022-11-15 17:17 UTC, jdsika commented
@royscheeren I cannot see any changes in the signing message:

![grafik](https://user-images.githubusercontent.com/11943343/201984299-cab5256c-2130-4256-898f-cec9945964ed.png)

2022-11-22 14:32 UTC, jdsika commented
I cannot see the policies in the message anymore. Please adjust the commands in Contribution.md on how to build this. I exchanged the line in index.js but I am confused by this message here:

> $ npm run demo:server:start
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> 
> > @stakenow/siwt@0.0.5 demo:server:start
> > dotenv -e .env node ./demo/server/index.js
> 
> SIWT server app listening on port 3000

2022-11-23 19:48 UTC, jdsika approved these changes

2022-11-24 09:31 UTC, merged