Feat/token acq
StakeNow/SIWT-Deprecated pull request #20
Opened 2022-11-18 11:10 UTC by royscheeren

# Scope

Allow the access control query to handle token balances

# Work done

Add an option for token balance to the access control query

This PR includes a refactor of the xtz balance access control query.

2022-11-21 13:16 UTC, jeroenbranje requested changes

2022-11-21 13:16 UTC, jeroenbranje commented on src/data/data.test.ts
> +      const result = await SUT._getLedgerFromStorage(httpStub as any)({
Can we give the correct type here instead of any?

2022-11-21 13:16 UTC, jeroenbranje commented on src/data/data.ts
> +          ([x, y]: number[]) => divide(y, 10 ** x),
You can make a utility of this denominate function and test it

2022-11-21 13:16 UTC, jeroenbranje commented on src/siwt.ts
> +import { getTokenBalance } from './data/data'
import from data/data lets define it in the index

2022-11-21 13:16 UTC, jeroenbranje commented on src/utils/siwt.utils.ts
> +export const filterOwnedAssetsFromNFTAssetContract = (pkh: string) => pipe(filter(propEq('value', pkh)))
Is pipe necessary here?

2022-11-21 13:16 UTC, jeroenbranje commented on src/utils/siwt.utils.ts
> +      filterOwnedAssetsFromNFTAssetContract(pkh) as any,
any type?

2022-11-21 13:16 UTC, jeroenbranje commented on src/utils/siwt.utils.ts
> +          passed: (COMPARISONS[comparator] as any)(prop('length')(ownedAssets))(value),
Is this any not an "Comparator" type

2022-11-21 15:11 UTC, royscheeren commented on src/data/data.test.ts
> +      const result = await SUT._getLedgerFromStorage(httpStub as any)({
no, its a test

2022-11-22 16:54 UTC, jeroenbranje submitted a review, later dismissed

2022-12-22 10:05 UTC, jeroenbranje approved these changes

2022-12-23 15:06 UTC, merged